import type { ScheduleData } from "./types";

export const scheduleData: ScheduleData = {
  faculty: "Управления и информатики в технологических системах",
  year: "2024-2025",
  semester: "Весенний семестр",
  groups: ["У-222", "У-223", "У-224"],
  lessons: [
    {
      id: "1",
      name: "Метрология",
      type: "practice",
      teacher: "Суханов П.М.",
      room: "чердак",
      subgroup: "both",
      week: "both",
      day: "ПОНЕДЕЛЬНИК",
      time: "08.00-09.35",
      group: "У-223",
    },
    {
      id: "6",
      name: "Методы и средства проектирования",
      type: "lecture",
      teacher: "Саввина Е.А.",
      room: "401",
      subgroup: "both",
      week: "both",
      day: "ПОНЕДЕЛЬНИК",
      time: "09.45-11.20",
      group: "У-223",
    },
    {
      id: "7",
      name: "Web-разработка",
      type: "lecture",
      teacher: "Бородина Е.А.",
      room: "401",
      subgroup: "both",
      week: "numerator",
      day: "ПОНЕДЕЛЬНИК",
      time: "11.50-13.25",
      group: "У-223",
    },
    {
      id: "8",
      name: "Современные фреймворки",
      type: "lecture",
      teacher: "Грек А.В.",
      room: "401",
      subgroup: "both",
      week: "denominator",
      day: "ПОНЕДЕЛЬНИК",
      time: "11.50-13.25",
      group: "У-223",
    },
    {
      id: "9",
      name: "Современные фреймворки",
      type: "practice",
      teacher: "Грек А.В.",
      room: "125",
      subgroup: 1,
      week: "numerator",
      day: "ПОНЕДЕЛЬНИК",
      time: "13.35-15.10",
      group: "У-223",
    },
    {
      id: "10",
      name: "Современные фреймворки",
      type: "practice",
      teacher: "Грек А.В.",
      room: "125",
      subgroup: 2,
      week: "denominator",
      day: "ПОНЕДЕЛЬНИК",
      time: "13.35-15.10",
      group: "У-223",
    },

    // У-222
    {
      id: "2",
      name: "План. и орг. произв. проц.",
      type: "lab",
      teacher: "Кондаурова О.В.",
      room: "151",
      subgroup: 2,
      week: "numerator",
      day: "ПОНЕДЕЛЬНИК",
      time: "08.00-09.35",
      group: "У-222",
    },
    {
      id: "3",
      name: "План. и орг. произв. проц.",
      type: "lab",
      teacher: "Кондаурова О.В.",
      room: "151",
      subgroup: 1,
      week: "denominator",
      day: "ПОНЕДЕЛЬНИК",
      time: "08.00-09.35",
      group: "У-222",
    },
    {
      id: "4",
      name: "Математика",
      type: "practice",
      teacher: "Чернышев А.Д.",
      room: "225",
      subgroup: 1,
      week: "numerator",
      day: "ПОНЕДЕЛЬНИК",
      time: "08.00-09.35",
      group: "У-222",
    },
    {
      id: "5",
      name: "Математика",
      type: "practice",
      teacher: "Чернышев А.Д.",
      room: "225",
      subgroup: 2,
      week: "denominator",
      day: "ПОНЕДЕЛЬНИК",
      time: "08.00-09.35",
      group: "У-222",
    },

  ],
};
